version: 2.1
jobs:
  build:
      docker:
        - image: circleci/node:8.11.2
      steps:
        - checkout
        - run:
            name: Update
            command: 'sudo npm install -g npm@latest'
        - run:
            name: Lint Application
            command: 'sudo npm run lint'

