version: 2.1
jobs:
  build:
      docker:
        - image: circleci/node:8.15.1
      steps:
        - checkout
        - run:
            name: Update NPM
            command: 'sudo npm install -g npm@latest'
        - run:
            name: Install Packages
            command: 'npm install'
        - run:
            name: Build App
            command: 'npm run build'

