version: 2.1
jobs:
  build:
      docker:
        - image: circleci/node:8.11.2
      steps:
        - checkout
        - run:
            name: Update and Install Packages
            command: 'sudo npm install'
        - run:
            name: Lint Application
            command: 'sudo npm run lint'

