version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
      docker:
        - image: circleci/node:8.15.1
      steps:
        - checkout
        - run:
            name: Update NPM
            command: 'sudo npm install -g npm@latest'
        - run:
            name: Install Packages
            command: 'npm install'
        - run:
            name: Build App
            command: 'npm run build'
        - aws-s3/sync:
            from: dist
            to: 's3://kidclampdown.com'
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            arguments: |
              --acl public-read \
              --cache-control "max-age=86400"
            overwrite: true
        - aws-s3/copy:
            from: dist/*
            to: 's3://kidclampdown.com'
            arguments: '--dryrun'
